const StatusBar = {
  LAYOUT_STATUS_BAR_CHANGE_COLOR: "LAYOUT_STATUS_BAR_CHANGE_COLOR",
  LAYOUT_STATUS_BAR_CHANGE: "LAYOUT_STATUS_BAR_CHANGE"
};

const GettingStarted = {
  GETTING_STARTED_CHANGED_STATE: "GETTING_STARTED_CHANGED_STATE"
};

const User = {
  LOGIN_CHANGE_STATE: "LOGIN_CHANGE_STATE",
  LOGIN_USER_DATA: "LOGIN_USER_DATA",
  LOGOUT: "LOGOUT"
};

export default {
  StatusBar,
  GettingStarted,
  User
};
